name = "jeyran-botmaker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "KV"
id = "PUT_YOUR_KV_ID_HERE"

[[d1_databases]]
binding = "DB"
database_name = "jeyran-db"
database_id = "PUT_YOUR_D1_ID_HERE"
